export const SESSION_STATUS = {
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
};

export const SESSION_CREATE_STATUS = {
  FAILED: 'FAILED',
  SUCCESS: 'SUCCESS',
  INITIAL: 'INITIAL',
};

export const SESSION_CURATE_TYPE = {
  OPEN: 'open',
  CURATED: 'curated',
};
